name: abci 
channels:
  - conda-forge
  - gpytorch
  - pytorch
  - defaults
dependencies:
  - botorch=0.5.1
  - cudatoolkit=10.2.89
  - jupyter=1.0.0
  - matplotlib=3.3.4
  - networkx=2.5
  - numpy=1.19.2
  - pip=21.2.2
  - python=3.7.10
  - pytorch=1.9.1
  - scikit-learn=1.0.2
  - scipy=1.6.1
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - pip:
      - cdt==0.5.23
      - gpytorch==1.5.1
      - pyro-ppl==1.7.0
